name: at-schreck-works/ddd-core (prod)

# master branch for ddd-core
on:
  workflow_dispatch:
  push:
    branches:
      - master

# test, build, and publish jobs
jobs:
  # test:
  #   name: test @schreck-works/ddd-core
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: checkout code
  #     uses: actions/checkout@master

  #   - name: set node environment
  #     uses: actions/setup-node@master
  #     with:
  #       always-auth: true
  #       node-version: '12.x'

  #   - name: install dependencies
  #     run: npm ci

  #   - name: run tests
  #     run: npm run test

  build-and-publish:
    # needs: [test]
    name: build & publish @schreck-works/ddd-core
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - name: checkout code
      uses: actions/checkout@master
      with:
        token: ${{ secrets.CI_TOKEN_ACTION }}

    - name: Bump version and push tag
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.CI_TOKEN_ACTION }}
        git-message: 'chore(release): {version}'
        preset: 'angular'
        tag-prefix: ''
        output-file: 'CHANGELOG.md'

    - name: set node environment
      uses: actions/setup-node@master
      with:
        always-auth: true
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org
        scope: '@schreck-works'

    - name: install dependencies
      run: npm ci

    - name: build library
      run: npm run build

    - name: publish library
      run: npm publish
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
